version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs-app
    ports:
      - '3001:3001'
    environment:
      DATABASE_URL: postgresql://postgres:loading1351@database-1.cn642oqegtt1.us-east-2.rds.amazonaws.com:5432/postgres
    volumes:
      - .:/my-nestjs-app

    command: >
      sh -c "npx prisma migrate deploy && npm run start:dev"
